# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode

  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thryft_development
  # username: postgres
  # password: <%= ENV["POSTGRES_PASSWORD"] %>
  # host: localhost

test:
  <<: *default
  database: thryft_test
  # username: postgres
  # password: <%= ENV["POSTGRES_PASSWORD"] %>
  # host: localhost

production:
  primary: &primary_production
    <<: *default
    database: thryft_production
    username: thryft
    password: <%= ENV["THRYFT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: thryft_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: thryft_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: thryft_production_cable
    migrations_paths: db/cable_migrate